version: 2
jobs:
  build:
    steps:
      - checkout

      # login to docker hub
      - run: docker login --username=$DOCKER_USER --password=$DOCKER_PASS

      # build the application image
      - run: docker build -t kimjoin2/study-cicd .

      # deploy the image to docker hub
      - run: docker push kimjoin2/study-cicd:latest

      # deploy to server
      - run: ssh $SSH_USER@$SSH_HOST "~/deployment.sh"
