version: 2
jobs:
  build_and_deploy_hub:
    # use linux machine for docker command
    machine: true
    steps:
      - checkout
      # login to docker hub
      - run:
          name: login docker hub
          command: docker login --username=$DOCKER_USER --password=$DOCKER_PASS
      # build the application image
      - run:
          name: build docker image
          command: docker build -t kimjoin2/study-cicd .
      # deploy the image to docker hub
      - run:
          name: deploy to docker hub
          command: docker push kimjoin2/study-cicd:latest

  deploy_server:
    machine: true
    steps:
      # deploy to server
      - run:
          name: deploy to server
          command: ssh $SSH_USER@$SSH_HOST "~/deployment.sh"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy_hub
      - deploy_server:
          requires:
            - build_and_deploy_hub
